GET http://localhost:3000/workouts


####

GET http://localhost:3000/workouts/1

###
POST http://localhost:3000/workouts
Content-Type: application/json

{
  "name": "leg press",
  "sets": 4,
  "reps": 12
}

###
PATCH http://localhost:3000/workouts/4
Content-Type: application/json

{
  "name": "The Leg Press"
}
###
DELETE http://localhost:3000/workouts/3

###
GET http://localhost:3000/users

###
GET http://localhost:3000/users/1

###
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Dan"
}
###

PATCH http://localhost:3000/users/3
Content-Type: application/json

{
  "name": "Danny"
}

###

DELETE http://localhost:3000/users/3